apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helm.fullname" . }}-configmap
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
data:
  SERVER_PORT: {{ .Values.configmap.SERVER_PORT | quote }}
  REPO_TYPE: {{ .Values.configmap.REPO_TYPE | quote }}
  REPO_URL: {{ .Values.configmap.REPO_URL | quote }}

