apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  REPO_ACCESS_TOKEN: {{ .Values.secrets.REPO_ACCESS_TOKEN | b64enc | quote }}
  REPO_KEY: {{ .Values.secrets.REPO_KEY | b64enc | quote }}
